PACKAGE_NAME="thunderbolt-tbfix"
PACKAGE_VERSION="1.4"

BUILT_MODULE_NAME[0]="thunderbolt"
BUILT_MODULE_LOCATION[0]="thunderbolt"
DEST_MODULE_LOCATION[0]="/updates"

BUILT_MODULE_NAME[1]="thunderbolt_net"
BUILT_MODULE_LOCATION[1]="thunderbolt_net"
DEST_MODULE_LOCATION[1]="/updates"

MAKE[0]="make KDIR=${kernel_source_dir}"
CLEAN="make KDIR=${kernel_source_dir} clean"

AUTOINSTALL="yes"
