#!/usr/bin/env bash
# Export the tbfix DKMS payload from this fork to the appmana repo (or any
# target dir). Produces a directory with the layout DKMS expects:
#
#   <target>/
#     dkms.conf
#     Makefile
#     thunderbolt/        <-- drivers/thunderbolt/ verbatim
#     thunderbolt_net/    <-- drivers/net/thunderbolt/ verbatim
#     .tbfix-source       <-- SHA + describe of the fork commit exported
#
# Default target is the in-fleet location:
#   appmana-management/src/appmana_management/files/thunderbolt_net/tbfix-dkms/
#
# The export is byte-identical when the fork branch matches the deployed
# DKMS payload. Drift is detected by `diff -r <target> <fork-export>`.

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
DEFAULT_TARGET="$(realpath "$REPO_ROOT/../appmana-management/src/appmana_management/files/thunderbolt_net/tbfix-dkms")"
TARGET="$DEFAULT_TARGET"

while (( $# > 0 )); do
  case "$1" in
    --target=*) TARGET="${1#--target=}";;
    --target)   shift; TARGET="$1";;
    -h|--help)
      cat <<USAGE
Usage: $0 [--target=PATH]

  --target=PATH  destination directory (default: $DEFAULT_TARGET)
USAGE
      exit 0
      ;;
    *)
      echo "unknown arg: $1" >&2; exit 1
      ;;
  esac
  shift
done

mkdir -p "$TARGET"
cd "$REPO_ROOT"

cp dkms/dkms.conf      "$TARGET/dkms.conf"
cp dkms/Makefile       "$TARGET/Makefile"

rm -rf "$TARGET/thunderbolt" "$TARGET/thunderbolt_net"
mkdir -p "$TARGET/thunderbolt" "$TARGET/thunderbolt_net"

# Use git archive so the export is reproducible from any commit, not the
# working tree (catches uncommitted local edits early).
git archive HEAD drivers/thunderbolt | tar -x -C "$TARGET/thunderbolt" --strip-components=2
git archive HEAD drivers/net/thunderbolt | tar -x -C "$TARGET/thunderbolt_net" --strip-components=3

{
  echo "# Auto-generated by scripts/export-dkms-payload.sh — do not edit"
  echo "fork-sha=$(git rev-parse HEAD)"
  echo "fork-describe=$(git describe --always --dirty)"
  echo "exported-at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$TARGET/.tbfix-source"

echo "Exported tbfix DKMS payload to $TARGET"
echo "  fork SHA: $(git rev-parse HEAD)"
