#!/usr/bin/env bash
# Export the tbfix DKMS payload from this fork to the appmana repo (or any
# target dir). Produces a directory with the layout DKMS expects:
#
#   <target>/
#     dkms.conf
#     Makefile
#     thunderbolt/        <-- drivers/thunderbolt/ verbatim
#     thunderbolt_net/    <-- drivers/net/thunderbolt/ verbatim
#     .tbfix-source       <-- SHA + describe of the fork commit exported
#
# Default target is the in-fleet location:
#   appmana-management/src/appmana_management/files/thunderbolt_net/tbfix-dkms/
#
# By default the export is byte-identical to HEAD. Use --worktree only for
# live validation of uncommitted driver changes; contribution-ready exports
# should be made from committed source.

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
DEFAULT_TARGET="$(realpath "$REPO_ROOT/../appmana-management/src/appmana_management/files/thunderbolt_net/tbfix-dkms")"
TARGET="$DEFAULT_TARGET"
SOURCE_REF=HEAD
USE_WORKTREE=0

while (( $# > 0 )); do
  case "$1" in
    --target=*) TARGET="${1#--target=}";;
    --target)   shift; TARGET="$1";;
    --ref=*)    SOURCE_REF="${1#--ref=}";;
    --ref)      shift; SOURCE_REF="$1";;
    --worktree) USE_WORKTREE=1;;
    -h|--help)
      cat <<USAGE
Usage: $0 [--target=PATH] [--ref=REV] [--worktree]

  --target=PATH  destination directory (default: $DEFAULT_TARGET)
  --ref=REV      export from a committed revision (default: HEAD)
  --worktree     export current working tree, including uncommitted edits
USAGE
      exit 0
      ;;
    *)
      echo "unknown arg: $1" >&2; exit 1
      ;;
  esac
  shift
done

mkdir -p "$TARGET"
cd "$REPO_ROOT"

if (( USE_WORKTREE == 0 )); then
  if ! git diff --quiet -- drivers/thunderbolt drivers/net/thunderbolt dkms; then
    echo "refusing to export: uncommitted DKMS-relevant edits are present" >&2
    echo "commit them first, or use --worktree for an explicit live-test export" >&2
    exit 1
  fi
fi

cp dkms/dkms.conf      "$TARGET/dkms.conf"
cp dkms/Makefile       "$TARGET/Makefile"

rm -rf "$TARGET/thunderbolt" "$TARGET/thunderbolt_net"
mkdir -p "$TARGET/thunderbolt" "$TARGET/thunderbolt_net"

if (( USE_WORKTREE == 1 )); then
  cp -a drivers/thunderbolt/. "$TARGET/thunderbolt/"
  cp -a drivers/net/thunderbolt/. "$TARGET/thunderbolt_net/"
else
  git archive "$SOURCE_REF" drivers/thunderbolt | tar -x -C "$TARGET/thunderbolt" --strip-components=2
  git archive "$SOURCE_REF" drivers/net/thunderbolt | tar -x -C "$TARGET/thunderbolt_net" --strip-components=3
fi

{
  echo "# Auto-generated by scripts/export-dkms-payload.sh — do not edit"
  echo "fork-sha=$(git rev-parse "$SOURCE_REF")"
  echo "fork-describe=$(git describe --always --dirty)"
  echo "source-ref=$SOURCE_REF"
  echo "source-worktree=$USE_WORKTREE"
  echo "exported-at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$TARGET/.tbfix-source"

echo "Exported tbfix DKMS payload to $TARGET"
echo "  fork SHA: $(git rev-parse "$SOURCE_REF")"
